package it.italiaonline.rnd.proxy

import groovy.util.logging.Slf4j

/**
 * This Groovy source file was auto generated by 'gigawatt'
 * @author d7392
 * @date 01-08-2018 12.55
 */
@Slf4j
class EnvProxy {
	/**
	 * This method returns always true.
	 */
	Boolean someEnvProxyMethod() {
		true
	}
}
