package it.italiaonline.rnd.proxy

import spock.lang.Specification

/**
 * This Spock specification was auto generated by 'gigawatt'
 * @author d7392
 * @date 01-08-2018 12.55
 */
class EnvProxySpec extends Specification {
	def "someEnvProxyMethod returns true"() {
		setup:
			EnvProxy lib = new EnvProxy()
		when:
			Boolean result = lib.someEnvProxyMethod()
		then:
			result == true
	}
}
